Repository vapor/async-kit, pull requests merged in 2020-02, with the labels that each got.

#52 Don't assert when a future in a queued sequence fails
  Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift
  Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
  Tests/AsyncKitTests/XCTestManifests.swift
Labels: bug, semver-patch

#54 Fix sequence-append in EventLoopFutureQueue
  Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift
  Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Labels: semver-patch

#55 Finish fixing sequence append for ELFQueue
  Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift
  Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Labels: semver-patch

#56 Return correct future when appending empty sequence
  Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift
  Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue.swift
  Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Labels: semver-patch

#57 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement
