Repository vapor/async-kit, pull requests merged in 2021-09, with the labels that each got.

#80 Add `strictMap()` and `EventLoopFuture.whenTheySucceed()`
  Sources/AsyncKit/EventLoopFuture/Future+Conjunctions.swift
  Sources/AsyncKit/EventLoopFuture/Optional+StrictMap.swift
  Tests/AsyncKitTests/Future+ConjunctionTests.swift
Labels: enhancement, semver-minor

#81 Add overload of flatMapEach(on:_:) for Void futures
  Sources/AsyncKit/EventLoopFuture/Future+Collection.swift
  Tests/AsyncKitTests/Future+CollectionTests.swift
Labels: semver-minor

#82 Add some more `EventLoopFuture<Collection>` utilities.
  Sources/AsyncKit/EventLoopFuture/Future+Collection.swift
  Tests/AsyncKitTests/Future+CollectionTests.swift
Labels: enhancement, semver-minor

#83 Add EventLoopFuture utility methods for handling empty collection values
  Sources/AsyncKit/EventLoopFuture/FutureExtensions.swift
  Tests/AsyncKitTests/FutureExtensionsTests.swift
Labels: enhancement

#84 Add `EventLoopFuture.tryFlatMap()` by popular demand
  Sources/AsyncKit/EventLoopFuture/Future+Try.swift
  Tests/AsyncKitTests/Future+TryTests.swift
Labels: semver-minor
